# Generated by Django 6.0.5 on 2026-06-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_abn_alter_contact_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bank_details',
            field=models.TextField(blank=True, default='', help_text='Bank account details sent in payment emails'),
        ),
    ]
