# Generated by Django 6.0.5 on 2026-06-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourbooking_return_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='is_admin_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
