# Generated by Django 6.0.5 on 2026-06-19 08:04

from django.db import migrations, models
from django.utils import timezone


def migrate_is_published_to_status(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for post in Blog.objects.all():
        if post.is_published:
            post.status = 'approved'
            if not post.published_at:
                post.published_at = timezone.now()
        else:
            post.status = 'draft'
        post.save(update_fields=['status', 'published_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full post body content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, default='', help_text='Custom meta description (overrides description field)', max_length=165),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Custom SEO title (overrides post title)', max_length=70),
        ),
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(help_text='Short description for meta + card snippet'),
        ),
        migrations.RunPython(migrate_is_published_to_status, migrations.RunPython.noop),
    ]
