# Generated by Django 6.0.5 on 2026-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_details_for_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_admin_booking',
            field=models.BooleanField(default=False),
        ),
    ]
