# Generated by Django 6.0.5 on 2026-06-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_admin_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='name',
            field=models.CharField(default='Sedan 1-5', max_length=100),
        ),
    ]
